#!/usr/bin/env bash
# xhs.sh — Xiaohongshu (小红书) atomic-operation helper for Agent Browser Runtime.
#
# Drives a persistent Chrome via `cli/brs.js` and parses pages with the bundled
# extractors/golddigger-xhs.extract.js (search / note / profile modes).
#
# Usage:
#   ./xhs.sh setup                       # Ensure Docker/runtime is up, open xiaohongshu (caches lease/tab)
#   ./xhs.sh search "<keyword>" [N]      # Search a keyword, print N notes (default 20)
#   ./xhs.sh read [index]                # Open the index-th note from the last search, print body + comments
#   ./xhs.sh profile <userId|profileUrl> # Open a user profile, print bio/stats + recent notes
#   ./xhs.sh open <noteUrl|noteId>       # (Fallback) navigate directly to a note (may 404 on stale xsec_token)
#
# Design notes:
#   - Search uses humanized UI: focus search box -> clear (.close-icon) -> type -> Enter.
#   - Opening a note MUST click a card on the search result page (section.note-item a.cover);
#     navigating directly to a note URL often fails xsec_token validation (300031/404),
#     because the token is generated by page JS when a card is clicked.
#   - Sensitive site: actions run serially with sleeps + humanize=enhanced.
#
# Requires: Agent Browser Runtime stack running (docker compose), a persistent
# Chrome profile that is logged in to xiaohongshu.com, and Python 3 (for formatting).
set -euo pipefail

# Resolve the repo root (this script lives in scripts/xiaohongshu/) regardless of CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BRS="$REPO_ROOT/cli/brs.js"
STATE="${TMPDIR:-/tmp}/brs_xhs_state.env"
OUT_SEARCH="${TMPDIR:-/tmp}/xhs_last_search.json"
OUT_NOTE="${TMPDIR:-/tmp}/xhs_last_note.json"
OUT_PROFILE="${TMPDIR:-/tmp}/xhs_last_profile.json"
AGENT="xhs-research"
TASK="xhs-search"

log(){ echo "[xhs] $*" >&2; }

ensure_docker(){
  if ! docker info >/dev/null 2>&1; then
    log "Docker not running; starting Docker Desktop..."
    open -a Docker 2>/dev/null || true
    for _ in $(seq 1 30); do docker info >/dev/null 2>&1 && break; sleep 5; done
  fi
}

ensure_runtime(){
  ensure_docker
  cd "$REPO_ROOT"
  if ! node "$BRS" status >/dev/null 2>&1; then
    log "Starting browser runtime stack..."
    docker compose up -d >/dev/null 2>&1 || true
  fi
  for _ in $(seq 1 15); do
    if node "$BRS" status 2>&1 | grep -q '"extensionConnected": true'; then
      log "runtime ready"; return 0
    fi
    sleep 6
  done
  log "Extension not connected; rebuilding..."
  docker compose up --build -d >/dev/null 2>&1 || true
  for _ in $(seq 1 15); do
    node "$BRS" status 2>&1 | grep -q '"extensionConnected": true' && { log "runtime ready after rebuild"; return 0; }
    sleep 8
  done
  log "ERROR: runtime still unavailable"; exit 1
}

# Open (or reuse) a xiaohongshu tab; sets LEASE and TAB.
ensure_tab(){
  cd "$REPO_ROOT"
  if [[ -f "$STATE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE"
    if [[ -n "${LEASE:-}" && -n "${TAB:-}" ]]; then
      if node "$BRS" tab-audit 2>/dev/null | grep -q "\"id\": $TAB"; then
        log "reusing lease=$LEASE tab=$TAB"; return 0
      fi
    fi
  fi
  log "Creating new lease and opening xiaohongshu..."
  local out
  out=$(node "$BRS" browse-start "https://www.xiaohongshu.com" --agent "$AGENT" --task "$TASK" 2>&1)
  LEASE=$(echo "$out" | grep -oE '"id": "lease_[^"]+"' | head -1 | sed 's/.*"lease_/lease_/;s/"//')
  TAB=$(echo "$out" | grep -oE '"id": [0-9]+' | head -1 | grep -oE '[0-9]+')
  echo "LEASE=$LEASE" > "$STATE"
  echo "TAB=$TAB" >> "$STATE"
  sleep 4
  log "lease=$LEASE tab=$TAB"
}

cmd_setup(){
  ensure_runtime
  ensure_tab
  echo "OK lease=$LEASE tab=$TAB"
}

# Humanized search: focus box -> clear -> type -> Enter.
cmd_search(){
  local kw="${1:?keyword required}"
  local n="${2:-20}"
  ensure_runtime; ensure_tab
  cd "$REPO_ROOT"
  # If stuck on a note overlay/other page, get back to a search page first.
  local seed
  seed=$(python3 -c 'import urllib.parse;print(urllib.parse.quote("健身房"))')
  node "$BRS" browse-nav "$LEASE" "$TAB" "https://www.xiaohongshu.com/search_result?keyword=$seed&source=web_search_result_notes&type=51" >/dev/null 2>&1 || true
  sleep 4
  # 1) focus the search box
  node "$BRS" ui "$TAB" click --selector "#search-input" >/dev/null 2>&1 || true
  sleep 1
  # 2) clear old query: prefer the .close-icon (×) button, then select-all + Delete
  node "$BRS" ui "$TAB" click --selector ".close-icon" >/dev/null 2>&1 || true
  sleep 1
  node "$BRS" ui "$TAB" click --selector "#search-input" >/dev/null 2>&1 || true
  sleep 1
  node "$BRS" ui "$TAB" press --key "Ctrl+A" >/dev/null 2>&1 || true
  node "$BRS" ui "$TAB" press --key "Delete" >/dev/null 2>&1 || true
  sleep 1
  # 3) type the keyword (humanized)
  node "$BRS" ui "$TAB" type --selector "#search-input" --text "$kw" >/dev/null 2>&1 || true
  sleep 1
  # 4) submit
  node "$BRS" ui "$TAB" press --key "Enter" >/dev/null 2>&1 || true
  log "searched: $kw; waiting for results..."
  sleep 5
  # 5) parse with the extractor (search mode scrolls/loads internally)
  node "$BRS" extract golddigger-xhs.extract.js \
      --lease-id "$LEASE" --tab-id "$TAB" \
      --params "{\"mode\":\"search\",\"maxNotes\":$n,\"maxSearchScrolls\":3}" \
      --humanize enhanced > "$OUT_SEARCH" 2>&1
  python3 "$SCRIPT_DIR/fmt.py" search "$OUT_SEARCH"
}

# Read the index-th note: click its card on the search result page, then extract.
cmd_read(){
  local idx="${1:-1}"
  ensure_runtime; ensure_tab
  cd "$REPO_ROOT"
  local sel="section.note-item:nth-of-type($idx) a.cover"
  log "clicking note card #$idx ..."
  node "$BRS" ui "$TAB" click --selector "$sel" >/dev/null 2>&1 || {
    log "nth-of-type click failed; falling back to first card";
    node "$BRS" ui "$TAB" click --selector "section.note-item a.cover" >/dev/null 2>&1 || true; }
  sleep 4
  node "$BRS" extract golddigger-xhs.extract.js \
      --lease-id "$LEASE" --tab-id "$TAB" \
      --params '{"mode":"note","commentScrollIterations":8,"maxExpandClicks":20}' \
      --humanize enhanced > "$OUT_NOTE" 2>&1
  python3 "$SCRIPT_DIR/fmt.py" note "$OUT_NOTE"
}

cmd_open(){
  local u="${1:?noteUrl or noteId required}"
  ensure_runtime; ensure_tab
  cd "$REPO_ROOT"
  [[ "$u" =~ ^http ]] || u="https://www.xiaohongshu.com/explore/$u"
  log "navigating directly: $u (may 404 on stale xsec_token)"
  node "$BRS" browse-nav "$LEASE" "$TAB" "$u" >/dev/null 2>&1 || true
  sleep 4
  node "$BRS" extract golddigger-xhs.extract.js \
      --lease-id "$LEASE" --tab-id "$TAB" \
      --params '{"mode":"note","commentScrollIterations":8,"maxExpandClicks":20}' \
      --humanize enhanced > "$OUT_NOTE" 2>&1
  python3 "$SCRIPT_DIR/fmt.py" note "$OUT_NOTE"
}

cmd_profile(){
  local u="${1:?profile URL or userId required}"
  ensure_runtime; ensure_tab
  cd "$REPO_ROOT"
  [[ "$u" =~ ^http ]] || u="https://www.xiaohongshu.com/user/profile/$u"
  log "opening profile: $u"
  node "$BRS" browse-nav "$LEASE" "$TAB" "$u" >/dev/null 2>&1 || true
  sleep 5
  for _ in 1 2 3; do
    node "$BRS" ui "$TAB" scroll --delta-y 900 >/dev/null 2>&1 || true
    sleep 1.5
  done
  node "$BRS" extract golddigger-xhs.extract.js \
      --lease-id "$LEASE" --tab-id "$TAB" \
      --params '{"mode":"profile"}' \
      --humanize enhanced > "$OUT_PROFILE" 2>&1
  python3 "$SCRIPT_DIR/fmt.py" profile "$OUT_PROFILE"
}

main(){
  local cmd="${1:-setup}"; shift || true
  case "$cmd" in
    setup) cmd_setup "$@" ;;
    search) cmd_search "$@" ;;
    read|read-note) cmd_read "$@" ;;
    open) cmd_open "$@" ;;
    profile|user) cmd_profile "$@" ;;
    *) echo "unknown command: $cmd (valid: setup|search|read|open|profile)" >&2; exit 1 ;;
  esac
}
main "$@"
